/* ============================================
   ShoeStore – Tablespace, Profile & Session Integration
   V5__db_tablespace_profile_session_integration.sql

   ============================================ */

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SESSION_AUDIT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW SECURITY_DB_CONTEXT';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION GET_SECURITY_CONTEXT';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

CREATE TABLE SESSION_AUDIT (
    SESSION_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER(10) NOT NULL,
    USERNAME NVARCHAR2(255) NOT NULL,
    LOGIN_AT TIMESTAMP NOT NULL,
    IP_ADDRESS NVARCHAR2(64),
    USER_AGENT NVARCHAR2(512),
    DB_USER NVARCHAR2(128),
    CLIENT_IDENTIFIER NVARCHAR2(128),
    CONSTRAINT FK_SESSION_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USERID)
);

COMMENT ON TABLE SESSION_AUDIT IS 'Logs application login sessions with database context information';
COMMENT ON COLUMN SESSION_AUDIT.SESSION_ID IS 'Primary key, auto-generated';
COMMENT ON COLUMN SESSION_AUDIT.USER_ID IS 'Foreign key to USERS table';
COMMENT ON COLUMN SESSION_AUDIT.USERNAME IS 'Application username (email)';
COMMENT ON COLUMN SESSION_AUDIT.LOGIN_AT IS 'Timestamp when user logged in';
COMMENT ON COLUMN SESSION_AUDIT.IP_ADDRESS IS 'Client IP address';
COMMENT ON COLUMN SESSION_AUDIT.USER_AGENT IS 'Client user agent string';
COMMENT ON COLUMN SESSION_AUDIT.DB_USER IS 'Oracle database user (from SYS_CONTEXT)';
COMMENT ON COLUMN SESSION_AUDIT.CLIENT_IDENTIFIER IS 'Oracle session client identifier';

CREATE INDEX IDX_SESSION_AUDIT_USER_ID ON SESSION_AUDIT(USER_ID);
CREATE INDEX IDX_SESSION_AUDIT_LOGIN_AT ON SESSION_AUDIT(LOGIN_AT DESC);

CREATE OR REPLACE VIEW SECURITY_DB_CONTEXT AS
SELECT
    SYS_CONTEXT('USERENV', 'SESSION_USER') AS SESSION_USER,
    SYS_CONTEXT('USERENV', 'CURRENT_USER') AS CURRENT_USER,
    SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
    SYS_CONTEXT('USERENV', 'HOST') AS HOST,
    SYS_CONTEXT('USERENV', 'IP_ADDRESS') AS DB_IP_ADDRESS,
    SYS_CONTEXT('USERENV', 'SESSIONID') AS SESSION_ID,
    SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER') AS CLIENT_IDENTIFIER,
    u.DEFAULT_TABLESPACE,
    u.TEMPORARY_TABLESPACE,
    'DEFAULT' AS PROFILE
FROM USER_USERS u;

COMMENT ON TABLE SECURITY_DB_CONTEXT IS 'Exposes current database session and user security context';

CREATE OR REPLACE FUNCTION GET_SECURITY_CONTEXT
RETURN VARCHAR2
IS
    v_context VARCHAR2(4000);
    v_user VARCHAR2(128);
    v_tablespace VARCHAR2(128);
    v_temp_tablespace VARCHAR2(128);
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_USER') INTO v_user FROM DUAL;

    SELECT DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
    INTO v_tablespace, v_temp_tablespace
    FROM USER_USERS
    WHERE ROWNUM = 1;

    v_context := 'DB_USER=' || v_user ||
                 ',DEFAULT_TABLESPACE=' || v_tablespace ||
                 ',TEMPORARY_TABLESPACE=' || v_temp_tablespace ||
                 ',PROFILE=DEFAULT';

    RETURN v_context;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'ERROR: ' || SQLERRM;
END GET_SECURITY_CONTEXT;
/
