CREATE TABLESPACE SHOE_DATA
  DATAFILE 'shoe_data01.dbf'
  SIZE 100M
  AUTOEXTEND ON NEXT 50M
  MAXSIZE UNLIMITED;

CREATE USER SHOE_APP
  IDENTIFIED BY "ChangeMeUser#123"
  DEFAULT TABLESPACE SHOE_DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON SHOE_DATA;

GRANT CONNECT, RESOURCE TO SHOE_APP;
GRANT CREATE SESSION TO SHOE_APP;
GRANT CREATE TABLE TO SHOE_APP;
GRANT CREATE SEQUENCE TO SHOE_APP;
GRANT CREATE VIEW TO SHOE_APP;
GRANT CREATE TRIGGER TO SHOE_APP;
GRANT CREATE PROCEDURE TO SHOE_APP;
GRANT CREATE TYPE TO SHOE_APP;

GRANT CREATE TABLE TO SHOE_APP;
GRANT CREATE VIEW TO SHOE_APP;
GRANT CREATE SEQUENCE TO SHOE_APP;

GRANT EXECUTE ON DBMS_RLS TO SHOE_APP;
GRANT EXECUTE ON DBMS_FGA TO SHOE_APP;
GRANT EXECUTE ON DBMS_CRYPTO TO SHOE_APP;

GRANT CREATE ROLE TO SHOE_APP;
GRANT DROP ANY ROLE TO SHOE_APP;

GRANT SELECT ON SYS.DBA_FGA_AUDIT_TRAIL TO SHOE_APP;