spring:
  application:
    name: shoestore-api
  profiles:
    default: dev

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  secret-key: ${JWT_SECRET_KEY:rCkoRPAEwHHe01qYBnuZ+UXzKpfMfvcQKCMbL+Uy0ULSUBVHPx6dyoKZEaD0mrrcHSoNB0ypVWjLpb39Q0SQAw==}
  expiration: 86400000