spring:
  application:
    name: shoestore-api
  profiles:
    default: dev

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  secret-key: ${JWT_SECRET_KEY:rCkoRPAEwHHe01qYBnuZ+UXzKpfMfvcQKCMbL+Uy0ULSUBVHPx6dyoKZEaD0mrrcHSoNB0ypVWjLpb39Q0SQAw==}
  expiration: 86400000

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:ShoeStoreAES128}

rsa:
  public-key: ${RSA_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmbIP7AgHRS2iJLoibJN6oJFe0iF+MZLJV5E4TMhTqoaOjsTCTUnQH+toXmpqZK7WI3spAIU+k83HoExdLHeJ/KEmkn7KjJjI1/yviRzsxKb1J8vU+jHhMn92O2GtXV/nTyoRA5dD15eQAMmJ6K+GNQjk6uAcHCJ3KAPwnma7OtI+t5dejV/2+HEwLCf0a7/x/NufHqFS2gnPZnxSXa/hTpSj33ujnCqozspQVeEHqaeeTEiYh2tJg+B4qUFTqGyOP/5ssDKemsIbORzz6LdZjaSUZx4iniOZzfbsNMdQx7muhodlBf2m7AkQAKD7vvlGDxf2BjnrXf1LeFbr1vb7CwIDAQAB}
  private-key: ${RSA_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZsg/sCAdFLaIkuiJsk3qgkV7SIX4xkslXkThMyFOqho6OxMJNSdAf62heampkrtYjeykAhT6TzcegTF0sd4n8oSaSfsqMmMjX/K+JHOzEpvUny9T6MeEyf3Y7Ya1dX+dPKhEDl0PXl5AAyYnor4Y1COTq4BwcIncoA/CeZrs60j63l16NX/b4cTAsJ/Rrv/H8258eoVLaCc9mfFJdr+FOlKPfe6OcKqjOylBV4Qepp55MSJiHa0mD4HipQVOobI4//mywMp6awhs5HPPot1mNpJRnHiKeI5nN9uw0x1DHua6Gh2UF/absCRAAoPu++UYPF/YGOetd/Ut4VuvW9vsLAgMBAAECggEABOxT9vbVDYNRyNk0x6B77Lr1h7CC9k/q1VObVhGTNrFTnvWq4jVytw03W7qDdHy4IXW7wtvHmhmFt3gMMRgWEaB5Txos/D1nLqnKhaaSFkSy1OslG1RhVZLx1MXXexI3upVw6ytvyrTZ96arka0/IGGXdoF9zb65+O9Bjj/s52llwxfwYnkAypyvaZ9rI7gQZKdZfThlsWApxt/MTPNDgjlPE+rAquTiKiKP9ah+fPFA0vyGI3PNMrR7QliIlYJFQ34oVmL3B3yOFVp7j5d0yPrxzXDrHjBU3R4eXDk+0gum5oWMYFGNkVnnZ4/HXv73yxasU/201+0xES5ZGpUVYQKBgQDAvPKeG4+qJoOLNZI201uNMGPIHXopNGKNOuM7rcwvTGU6FWZD9EiQpM5cmFkun4c4RTWzlgYlCS9zmbMTmJiYBsOoO7ml7ZeoaQlaRQRn/ZBjMT8lHhXPzyrOt9M7FHHpZKr0hDJ2hQzlXczTidn7zEtZtAKdvyhxROd/ft6xPQKBgQDMJITX1JOjVqX1bs/fLjIjTaFZ1u3H1DXXG3x/mm+AYhdO/SqtJXRj72fDjjRJAuK4yhGmBWyDVisrsdZDUONG+zfRKOf4VUgZzXra+MhcPxg+M13KkZe6E4qjTME/6fdCI9igkgKceFgAEGogdrA42VBLu6P6aJ2+gbrif0AR5wKBgCq+/TQxuqgrCIusYvRD5g8nR0oPt5NB6gWWpOUMg7eNwvmh21+A40MpOhdxNn5PpUbGmsVspYo7QknqMbxL4LP+9A/wxxjU3Aje2tMpcXO62fYV6wJJbN78/GqCfJeizizMRdobI7IDijuolQ/ph+3/fkqz0My5o7eTZ6BwO+WlAoGBALkF9F1GL1Xgp+ROPhuy3ACBUNeDZNoz7WR8ZhelWqAKx8Nw1ChAhUA6cVqd3ae69NC1XM+TpOlYxSICOgejHYttEAcDw1OhwAqa4VnsGHT7PrbJiZ2a3eDp60Lcw15xaQhKQwIttC4rKN9OAVJRIKE13X/2nsXL4gUTwdWdre1LAoGANPIyxKcfWmgrSh9DDp5zPMpPILRXV4jNUotvp3TSAz930PHoY1TYOSXwqp0oksmSKLX2oxWPUTMtEwDiDj8k87zkTUU3ApCzTAXM9jicKaoiSHBTA1osWUipXDaTwhRfJJtQTH6s8nWidqk7RzOuad6Zcw/qZvE8XgeoR/+6F+E=}