export const VIETNAMESE_PROVINCES = [
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Ninh",
  "Bình Định",
  "Bình Thuận",
  "Cao Bằng",
  "Đà Nẵng",
  "Điện Biên",
  "Đồng Nai",
  "Hà Giang",
  "Hà Nội",
  "Hà Tĩnh",
  "Hòa Bình",
  "Hồ Chí Minh",
  "Huế",
  "Khánh Hòa",
  "Lai Châu",
  "Lạng Sơn",
  "Long An",
  "Nghệ An",
  "Ninh Thuận",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sơn La",
  "Thái Nguyên",
] as const;

export type VietnameseProvince = typeof VIETNAMESE_PROVINCES[number];
